import random

jokes = [
    "Why don’t scientists trust atoms? Because they make up everything!",
    "Why was the math book sad? It had too many problems.",
    "What do you call fake spaghetti? An impasta!",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "Why did the bicycle fall over? Because it was two-tired!",
    "What did one wall say to the other? I’ll meet you at the corner!",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one!",
    "What do you call cheese that isn’t yours? Nacho cheese!",
    "Why couldn’t the leopard play hide and seek? Because he was always spotted.",
    "What did the fish say when he hit the wall? Dam!",
    "Why did the cookie go to the hospital? Because it felt crummy!",
    "What do you call a belt made of watches? A waist of time!",
    "Why did the stadium get hot after the game? Because all the fans left!",
    "How does a penguin build its house? Igloos it together!",
    "What’s orange and sounds like a parrot? A carrot!",
    "Why can’t you give Elsa a balloon? Because she will let it go!",
    "What do you get from a pampered cow? Spoiled milk!",
    "Why was the computer cold? It left its Windows open!",
    "How does the ocean say hello? It waves!",
    "What do you call an alligator in a vest? An investigator!",
    "Why did the picture go to jail? Because it was framed!",
    "What do you call a bear with no teeth? A gummy bear!",
    "Why don’t programmers like nature? It has too many bugs.",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "What did the janitor say when he jumped out of the closet? Supplies!",
    "Why was the belt arrested? For holding up a pair of pants!",
    "How does a scientist freshen her breath? With experi-mints!",
    "Why did the golfer bring an extra shirt? In case he got a hole in one!",
    "What do you call a snowman with a six-pack? An abdominal snowman!",
    "Why did the coffee file a police report? It got mugged!",
    "What kind of music do balloons hate? Pop music!",
    "Why did the man put his money in the blender? Because he wanted to make some liquid assets!",
    "What did one hat say to the other? You stay here; I’ll go on ahead!",
    "Why can’t you trust stairs? Because they’re always up to something!",
    "What do you call a fish with no eyes? Fsh!",
    "Why did the tomato turn red? Because it saw the salad dressing!",
    "What did one snowman say to the other? Do you smell carrots?",
    "How do you organize a space party? You planet!",
    "Why did the banker switch careers? He lost interest!",
    "What's brown and sticky? A stick!",
    "What did the ocean say to the beach? Nothing, it just waved!",
    "Why did the math teacher break up with the history teacher? Because they had too many problems!",
    "How does a vampire start a letter? Tomb it may concern...",
    "Why don’t oysters donate to charity? Because they are shellfish!",
    "Why did the student eat his homework? Because the teacher said it was a piece of cake!",
    "Why did the dinosaur cross the road? Because chickens didn’t exist yet!",
    "How do you catch a squirrel? Climb a tree and act like a nut!",
    "What do you call a dog magician? A labracadabrador!",
    "Why don’t some couples go to the gym? Because some relationships don’t work out!",
]

def get_random_joke():
    return random.choice(jokes)